"""update product table

Revision ID: 0145b4c56bdb
Revises: 29a6561b149a
Create Date: 2023-07-05 14:17:22.263193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0145b4c56bdb'
down_revision = '29a6561b149a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_colour_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'colour_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('colour_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_colour_id_fkey', 'products', 'colour', ['colour_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
