"""product table update

Revision ID: 035684d6bbc0
Revises: 0da66182d118
Create Date: 2023-06-27 11:34:56.079545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035684d6bbc0'
down_revision = '0da66182d118'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('colour', sa.String(), nullable=True))
    op.drop_column('products', 'color')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('products', 'colour')
    # ### end Alembic commands ###
