"""Upgrade model

Revision ID: 0aae46d26763
Revises: 2b80085fcdd5
Create Date: 2023-06-26 13:52:03.108557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aae46d26763'
down_revision = '2b80085fcdd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ordered_products_product_id_fkey', 'ordered_products', type_='foreignkey')
    op.drop_constraint('ordered_products_order_id_fkey', 'ordered_products', type_='foreignkey')
    op.drop_column('ordered_products', 'order_id')
    op.drop_column('ordered_products', 'product_id')
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('ordered_products', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ordered_products', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('ordered_products_order_id_fkey', 'ordered_products', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('ordered_products_product_id_fkey', 'ordered_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
