"""product table update

Revision ID: 0da66182d118
Revises: 3c71088c3ce0
Create Date: 2023-06-27 11:34:19.678528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da66182d118'
down_revision = '3c71088c3ce0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('procent_sale', sa.Integer(), nullable=True))
    op.drop_column('products', 'percent_sale')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('percent_sale', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('products', 'procent_sale')
    # ### end Alembic commands ###
