"""update product model

Revision ID: 110f5d7354a0
Revises: 8f1873a5e9cd
Create Date: 2023-07-01 12:14:32.158992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110f5d7354a0'
down_revision = '8f1873a5e9cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
