"""add new table promocode FK

Revision ID: 1824b7f5101b
Revises: 4851ac89c66e
Create Date: 2023-07-07 18:20:11.111802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1824b7f5101b'
down_revision = '4851ac89c66e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promocode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('procent', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promocode_id'), 'promocode', ['id'], unique=False)
    op.add_column('products', sa.Column('promocode_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'promocode', ['promocode_id'], ['id'], ondelete='SET NULL')
    op.drop_column('products', 'promocode_procent')
    op.drop_column('products', 'promocode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('promocode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('promocode_procent', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'promocode_id')
    op.drop_index(op.f('ix_promocode_id'), table_name='promocode')
    op.drop_table('promocode')
    # ### end Alembic commands ###
