"""add visible to product model

Revision ID: 241c48eab202
Revises: 287861dcb3eb
Create Date: 2023-07-23 15:01:23.810662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241c48eab202'
down_revision = '287861dcb3eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('visible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'visible')
    # ### end Alembic commands ###
