"""modified user model

Revision ID: 287861dcb3eb
Revises: d0de4392a480
Create Date: 2023-07-14 09:32:25.118828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287861dcb3eb'
down_revision = 'd0de4392a480'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('born', sa.DateTime(), nullable=True))
    op.drop_column('users', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'born')
    # ### end Alembic commands ###
