"""update product table

Revision ID: 29a6561b149a
Revises: d022a3bb0ff2
Create Date: 2023-07-04 16:12:06.219864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a6561b149a'
down_revision = 'd022a3bb0ff2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('colour_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'colour', ['colour_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'colour_id')
    # ### end Alembic commands ###
