"""add new row promocode

Revision ID: 3459edb7f6e9
Revises: 8b7358482669
Create Date: 2023-07-08 11:51:35.778808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3459edb7f6e9'
down_revision = '8b7358482669'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
