"""add data

Revision ID: 361f981a0979
Revises: 241c48eab202
Create Date: 2023-08-02 11:06:11.365292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361f981a0979'
down_revision = '241c48eab202'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###alembic revision --autogenerate -m "add data"
    op.add_column('admins', sa.Column('born', sa.DateTime(), nullable=True))
    op.drop_column('admins', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('admins', 'born')
    # ### end Alembic commands ###
