"""add all models v2 

Revision ID: 423b49540803
Revises: 730d6d4766e1
Create Date: 2023-07-02 16:20:51.451476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423b49540803'
down_revision = '730d6d4766e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('colour_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'colour', ['colour_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'colour_id')
    # ### end Alembic commands ###
