"""add new row to Product 

Revision ID: 4851ac89c66e
Revises: fac681b22a6b
Create Date: 2023-07-07 13:57:27.817361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4851ac89c66e'
down_revision = 'fac681b22a6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('promocode_procent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'promocode_procent')
    # ### end Alembic commands ###
