"""add photo model v2

Revision ID: 4e3d8d17f46b
Revises: 938825c468d1
Create Date: 2023-06-19 12:40:07.158994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3d8d17f46b'
down_revision = '938825c468d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
