"""order table update

Revision ID: 59faab78cf33
Revises: 7c2b9ab9db63
Create Date: 2023-06-29 14:34:03.515164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59faab78cf33'
down_revision = '7c2b9ab9db63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'count')
    # ### end Alembic commands ###
