"""product table update

Revision ID: 7c2b9ab9db63
Revises: a05799ce33ee
Create Date: 2023-06-27 12:18:04.163098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c2b9ab9db63'
down_revision = 'a05799ce33ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_owner_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'admins', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_owner_fkey', 'products', 'users', ['owner'], ['id'])
    # ### end Alembic commands ###
