"""modifie admin model

Revision ID: 829ef14584da
Revises: a4bed84a7c69
Create Date: 2023-06-18 10:36:14.343127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829ef14584da'
down_revision = 'a4bed84a7c69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admins_gmail_key', 'admins', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('admins_gmail_key', 'admins', ['gmail'])
    # ### end Alembic commands ###
