"""add new row promocode

Revision ID: 8b7358482669
Revises: 93c1e561e64d
Create Date: 2023-07-08 11:40:20.379402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b7358482669'
down_revision = '93c1e561e64d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promocode', sa.Column('category', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'promocode', 'category', ['category'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promocode', type_='foreignkey')
    op.drop_column('promocode', 'category')
    # ### end Alembic commands ###
