"""update all tables

Revision ID: 8f1873a5e9cd
Revises: 10c4369fc4af
Create Date: 2023-06-30 10:18:36.642630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1873a5e9cd'
down_revision = '10c4369fc4af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ordered_products_product_id_fkey', 'ordered_products', type_='foreignkey')
    op.create_foreign_key(None, 'ordered_products', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('products_owner_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'admins', ['owner'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_owner_fkey', 'products', 'admins', ['owner'], ['id'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'ordered_products', type_='foreignkey')
    op.create_foreign_key('ordered_products_product_id_fkey', 'ordered_products', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
