"""add photo model

Revision ID: 938825c468d1
Revises: cdf913add491
Create Date: 2023-06-19 11:09:32.977040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938825c468d1'
down_revision = 'cdf913add491'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('product', 'photos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('photos', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('image')
    # ### end Alembic commands ###
