"""add new table promocode FK

Revision ID: 93c1e561e64d
Revises: 1824b7f5101b
Create Date: 2023-07-07 18:25:21.909042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c1e561e64d'
down_revision = '1824b7f5101b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
