"""product table update

Revision ID: a05799ce33ee
Revises: 035684d6bbc0
Create Date: 2023-06-27 11:37:45.504037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05799ce33ee'
down_revision = '035684d6bbc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
