"""add Delite cascade

Revision ID: a4bed84a7c69
Revises: aaeb31c3edd5
Create Date: 2023-06-18 09:58:52.598927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4bed84a7c69'
down_revision = 'aaeb31c3edd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ordered_products_order_id_fkey', 'ordered_products', type_='foreignkey')
    op.create_foreign_key(None, 'ordered_products', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('product_owner_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'admins', ['owner'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_owner_fkey', 'product', 'admins', ['owner'], ['id'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'ordered_products', type_='foreignkey')
    op.create_foreign_key('ordered_products_order_id_fkey', 'ordered_products', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
