"""update product model

Revision ID: a50ada407acb
Revises: 110f5d7354a0
Create Date: 2023-07-01 12:16:02.543593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50ada407acb'
down_revision = '110f5d7354a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
