"""add all relationships and FK

Revision ID: aaeb31c3edd5
Revises: 6f2f9829810c
Create Date: 2023-06-17 11:42:58.674168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aaeb31c3edd5'
down_revision = '6f2f9829810c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('Category', sa.String(), nullable=False),
    sa.Column('photos', sa.String(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('procent_sale', sa.Integer(), nullable=True),
    sa.Column('promocode', sa.String(), nullable=True),
    sa.Column('Colour', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Product')
    op.add_column('ordered_products', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ordered_products', 'orders', ['order_id'], ['id'])
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'user_id')
    op.drop_constraint(None, 'ordered_products', type_='foreignkey')
    op.drop_column('ordered_products', 'order_id')
    op.create_table('Product',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Product_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('photos', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('procent_sale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('promocode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Colour', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Product_pkey')
    )
    op.drop_table('product')
    # ### end Alembic commands ###
