"""product table update

Revision ID: b8931bf05d6f
Revises: 3c8da2993c8e
Create Date: 2023-06-27 11:30:03.683856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8931bf05d6f'
down_revision = '3c8da2993c8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ordered_products_product_id_fkey', 'ordered_products', type_='foreignkey')
    op.drop_constraint('ordered_products_order_id_fkey', 'ordered_products', type_='foreignkey')
    op.create_foreign_key(None, 'ordered_products', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'ordered_products', 'orders', ['order_id'], ['id'])
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.alter_column('products', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'color',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint('products_owner_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_owner_id_fkey', 'products', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('products', 'color',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'ordered_products', type_='foreignkey')
    op.drop_constraint(None, 'ordered_products', type_='foreignkey')
    op.create_foreign_key('ordered_products_order_id_fkey', 'ordered_products', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('ordered_products_product_id_fkey', 'ordered_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
