"""add colour model and Fk to Product model 

Revision ID: c81e3c06e147
Revises: 503327c84eb8
Create Date: 2023-07-02 12:30:16.051071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81e3c06e147'
down_revision = '503327c84eb8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colour_id'), 'colour', ['id'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.drop_column('products', 'colour')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('colour', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_colour_id'), table_name='colour')
    op.drop_table('colour')
    # ### end Alembic commands ###
