"""modifie admin model v2

Revision ID: cdf913add491
Revises: 829ef14584da
Create Date: 2023-06-18 17:15:53.060594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf913add491'
down_revision = '829ef14584da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category', sa.String(), nullable=False))
    op.add_column('product', sa.Column('colour', sa.String(), nullable=False))
    op.drop_column('product', 'Colour')
    op.drop_column('product', 'Category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('Category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('Colour', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('product', 'colour')
    op.drop_column('product', 'category')
    # ### end Alembic commands ###
