"""update product table

Revision ID: d022a3bb0ff2
Revises: 423b49540803
Create Date: 2023-07-04 15:36:42.945860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd022a3bb0ff2'
down_revision = '423b49540803'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colour_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('colour_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['colour_id'], ['colour.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colour_product_id'), 'colour_product', ['id'], unique=False)
    op.drop_constraint('products_colour_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'colour_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('colour_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_colour_id_fkey', 'products', 'colour', ['colour_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_colour_product_id'), table_name='colour_product')
    op.drop_table('colour_product')
    # ### end Alembic commands ###
