"""add new row to order model

Revision ID: d0de4392a480
Revises: 3459edb7f6e9
Create Date: 2023-07-08 13:30:10.335519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0de4392a480'
down_revision = '3459edb7f6e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('promocode', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'promocode', ['promocode'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'promocode')
    # ### end Alembic commands ###
