"""add Cascade

Revision ID: fac681b22a6b
Revises: 0145b4c56bdb
Create Date: 2023-07-07 10:38:12.834347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac681b22a6b'
down_revision = '0145b4c56bdb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('colour_product_product_id_fkey', 'colour_product', type_='foreignkey')
    op.drop_constraint('colour_product_colour_id_fkey', 'colour_product', type_='foreignkey')
    op.create_foreign_key(None, 'colour_product', 'colour', ['colour_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'colour_product', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'colour_product', type_='foreignkey')
    op.drop_constraint(None, 'colour_product', type_='foreignkey')
    op.create_foreign_key('colour_product_colour_id_fkey', 'colour_product', 'colour', ['colour_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('colour_product_product_id_fkey', 'colour_product', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
