#version: "3.7"
#services:
#  db:
#    image: postgres:15
#    container_name: db_app
#    # command: -p 1221
#    ports:
#      - 5432
#    env_file:
#      - api/.env-non-dev

#  app:
#      build:
#        context: .
#      env_file:
#        - api/.env
#      container_name: market-palace
##      command: ["api/docker/app.sh"]
#      ports:
#        - 9999:8000
#      depends_on:
#        - db
  version: "3.3"

  services:
    db:
      image: postgres:15
      container_name: db_app
      ports:
        - 5432
      env_file:
        - api/.env-non-dev


    app:
      build:
        context: .
      env_file:
        - api/.env
      container_name: market-palace
      ports:
        - "9999:8000"
      depends_on:
        - db
#      command: sh -c 'sleep 5 && python main.py'
